### ISSUE TITLE
Seems to require Silverstripe/Blog dependency

### ISSUE THREAD

**Issue by MattyBalaam** [xddesigners/silverstripe-events#1]
Adding a page in admin throws a 500 error.

EventsLumberjack.php is requiring the following: **SilverStripe\Blog\Model\BlogFilter\BlogFilterGridField**

**Comment by TheBnl** [comment]
Hi Matty,

Sharp, always used the module together with the blog. 
I'll remove the import!

**Comment by TheBnl** [comment]
The import is removed and a release is tagged!
