### ISSUE TITLE
Internal Server Error on archiv event

### ISSUE THREAD

**Issue by grasn** [xddesigners/silverstripe-events#3]
Hey,
I'm using SS 4.3.3. If I try to archiv an Event Page, i get an Internal Server Error message from SS on the top right side. I enabled debug log, but there is no log event for the error.

**Comment by RVXD** [comment]
Hi Grasn, we have fixed this in the latest version. If you update, the error is gone.

**Comment by grasn** [comment]
Thanks man, now it is working fine!
